### ISSUE TITLE
Implement version tagging?

### ISSUE THREAD

**Issue by WillTheDeveloper** [colsak/GradeCalculator#6]
Should we implement version tagging? If this ever gets used out in the *wild* then it probably be good if we versioned it? It's not too far from beta/production ready state.

**Comment by tokorv** [comment]
I think don't think it's a bad idea but releases should have library documentation and shared libraries (dynamic) for Linux, Windows, and MacOS (or at least contain instructions on how to compile to get the library binaries).

**Comment by WillTheDeveloper** [comment]
Okay, fair enough. So what your saying is, we need to document it all first and ensure that the program can run on all different operating systems?

**Comment by tokorv** [comment]
Yeah, there are probably some documentation libraries for C++ where you can generate docs through comments in code. Maybe [Doxygen](https://www.doxygen.nl/manual/faq.html)?

**Comment by WillTheDeveloper** [comment]
Nah. Just do it manually. For what its worth, we will only have to document it once and change it like once a year or something. The grade stuff doesn't change a lot and if anything, a new one could get added but it could always be added by community or by ourselves.
